// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWBseR_NFujTp3W36enMVGX3fzEsLaCpo',
    appId: '1:259025625451:web:4b0a5a514a910074296c2e',
    messagingSenderId: '259025625451',
    projectId: 'cyber-vault',
    authDomain: 'cyber-vault.firebaseapp.com',
    storageBucket: 'cyber-vault.appspot.com',
    measurementId: 'G-CSJ7PMTH5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNCiCXniWS8p8WrHNR9NSAvtNe5c8gtU',
    appId: '1:259025625451:android:7ca6ece19775c889296c2e',
    messagingSenderId: '259025625451',
    projectId: 'cyber-vault',
    storageBucket: 'cyber-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Xfc0xpoz32VKsJ8sNzDxR1JitBlUVkg',
    appId: '1:259025625451:ios:edf4e69b375e5a45296c2e',
    messagingSenderId: '259025625451',
    projectId: 'cyber-vault',
    storageBucket: 'cyber-vault.appspot.com',
    iosBundleId: 'com.example.cyberVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Xfc0xpoz32VKsJ8sNzDxR1JitBlUVkg',
    appId: '1:259025625451:ios:d237cdf8a551f217296c2e',
    messagingSenderId: '259025625451',
    projectId: 'cyber-vault',
    storageBucket: 'cyber-vault.appspot.com',
    iosBundleId: 'com.example.cyberVault.RunnerTests',
  );
}
